### ISSUE TITLE
allow command + click to homepage cards

### ISSUE THREAD

**Issue by cdt-eth** [cdt-eth/Nouns-Center#37]
if i click, open target="_self", if i command click, allow open in new tab (target="_blank")

something like:
```
// util funcs
export const cmdPlusClicked = (e: any) => e.metaKey || e.ctrlKey;
export const openInNewTab = (url: string) => window.open(url, `_blank`);

<div onClick={e => {
    if (cmdPlusClicked(e)) {
        openInNewTab(`${path}`);
        return;
    }
    navigate(`${path}`);
}}>
```

**Comment by ryeshrimp** [comment]
@cdt-eth I think you can just wrap an anchor around Link to fix this.

```
<Link>
    <a />
</Link>
```

**Comment by cdt-eth** [comment]
ah yes, was referencing how we had to do it with prop house (bootstrap), but nextjs has <Link>'s, youre right @ryeshrimp
